# Redirect Netlify domain to tomherni.dev
[[redirects]]
  from = "https://tomherni.netlify.app"
  to = "https://tomherni.dev"
  force = true

# Redirect .com domain (without www.) to tomherni.dev
[[redirects]]
  from = "https://tomherni.com"
  to = "https://tomherni.dev"
  force = true

# Redirect .com domain (with www.) to tomherni.dev
[[redirects]]
  from = "https://www.tomherni.com"
  to = "https://tomherni.dev"
  force = true

# Redirect non-existent pages to the homepage
[[redirects]]
  from = "/*"
  to = "https://tomherni.dev"
