name: Node.js CI

on:
  push:
    branches:
      - ci
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
      NODE_VERSION: '18.x'
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint:check
      - name: Check formatting
        run: npm run format:check
      - name: Build
        run: npm run build
